name: linter-checker
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: poetry install
        run: pip install poetry
      - name: install dependencies
        run: make install
      - name: flake8
        run: make lint
