name: Linter-cheker

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          pip install poetry
          make install
      - name: flake8
        run: |
          make lint
